name: dartbook
description: A dart implementation of gitbook-cli for guys who loves writing.
version: 1.0.0
homepage: https://github.com/lindeer/dartbook

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  dartbook:
  dartbook-diff: diff

dependencies:
# functional
  path: 1.8.2
  collection: 1.16.0
  markdown:
    git:
      url: https://github.com/lindeer/markdown.git
      ref: t/footnote
  json_schema2: ^2.0.2+6
  jinja: ^0.4.2
  html: ^0.15.0
  shelf_static: ^1.1.1
  shelf: ^1.3.2
  watcher: ^1.0.1
  args: ^2.3.1
  diff_match_patch: ^0.4.1
  glob: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
