name: dartbook
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  markdown: 5.0.0
  html: 0.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
