name: dartbook
description: A dart implementation of gitbook-cli for guys who loves writing.
version: 1.2.0
homepage: https://github.com/lindeer/dartbook

environment:
  sdk: '>=3.0.0<4.0.0'

executables:
  dartbook:
  dartbook-diff: diff

dependencies:
# functional
  path: ^1.8.2
  collection: ^1.16.0
  markdown: ^7.1.0
  json_schema: ^5.0.0
  jinja: ^0.6.0
  html: ^0.15.0
  shelf_static: ^1.1.1
  shelf: ^1.3.2
  args: ^2.3.1
  diff_match_patch: ^0.4.1
  glob: ^2.1.1
  dartbook_theme_default: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
