name: dartbook
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
# functional
  path: 1.8.2
  collection: 1.16.0
  dart_markdown: ^2.0.0
  dartbook_html:
    path: ../html
  dartbook_models:
    path: ../models
  json_schema2: ^2.0.2+6
  jinja:
    git:
      url: https://lindeer:cljs118!@gitee.com/lindeer/jinja.dart.git
      ref: main
  html: ^0.15.0
  shelf_static: ^1.1.1
  shelf: ^1.3.2
  watcher: ^1.0.1
  args: ^2.3.1
  diff_match_patch: ^0.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
