name: dartbook
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
# functional
  path: 1.8.2
  collection: 1.16.0
  markdown: 5.0.0
  dartbook_html:
    path: ../html
  dartbook_models:
    path: ../models

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
