name: dartbook_html
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
# fundamental util
  collection: 1.16.0
# functional
  html: 0.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
