name: dartbook_models
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartbook_html:
    path: ../html
  path: 1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
